name: CI

on: [push] # git push をトリガーとする

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_11.app/Contents/Developer'
    - name: Show Xcode version
      run: xcodebuild -version
    - name: Test
      #run: xcodebuild -sdk iphonesimulator -configuration Debug build 
      run: xcodebuild test -sdk iphonesimulator -configuration Debug -target todoTests  -scheme todoTests -destination 'platform=iOS Simulator,name=Generic iOS Simulator Device'
